apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-alerts
    receivers:
      - uid: email-alerts-receiver
        type: email
        settings:
          addresses: khaliqbaloch009@gmail.com
          singleEmail: true

policies:
  - orgId: 1
    receiver: email-alerts
    group_by: ["grafana_folder", "alertname"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
